version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/django_BrainBlasters
    command: "python ./django_BrainBlasters/manage.py runserver 0.0.0.0:8000"
