# Generated by Django 5.0.7 on 2024-07-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario_groups_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
