# Generated by Django 5.0.7 on 2024-08-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='ganador',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='ganador1',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='ganador2',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='ganador3',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Premio',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.DeleteModel(
            name='Sorteo',
        ),
        migrations.DeleteModel(
            name='Trivia',
        ),
    ]
