# Generated by Django 5.0.7 on 2024-08-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_usuario_options_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='modified_by',
        ),
    ]
