# Generated by Django 5.0.7 on 2024-08-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_usuario_created_by_usuario_modified_by_jugador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='pregunta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='categoria',
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_img1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_img3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_img4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_txt1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_txt2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_txt3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='opcion_txt4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='respuesta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trivia',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='premio',
            name='ganador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador'),
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
