# Generated by Django 5.0.7 on 2024-08-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_trivia_pregunta_remove_ranking_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria'),
        ),
    ]
