# Generated by Django 5.0.7 on 2024-08-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_trivia_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trivia',
        ),
    ]
