# Generated by Django 5.0.7 on 2024-08-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_trivia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='ganador',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='ganador1',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='ganador2',
        ),
        migrations.RemoveField(
            model_name='sorteo',
            name='ganador3',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Premio',
        ),
        migrations.DeleteModel(
            name='Sorteo',
        ),
        migrations.DeleteModel(
            name='Trivia',
        ),
    ]
