# Generated by Django 5.0.7 on 2024-08-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_jugador_premio_sorteo_trivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='descripcion_img1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='descripcion_img2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='descripcion_img3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='descripcion_img4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img1',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img2',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img3',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img4',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
