# Generated by Django 5.0.7 on 2024-08-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_trivia_descripcion_img1_trivia_descripcion_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
