# Generated by Django 5.0.7 on 2024-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_trivia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img3',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='opcion_img4',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
