# Generated by Django 5.0.7 on 2024-08-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_categoria_frecuencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='frecuencia',
        ),
    ]
